
reference:
  include_nonchromosomal: False

simulation:
  read_length: 100
  fragment_mean: 300
  fragment_stddev: 30
  coverage: 10
  coverage_fraction: 0.25
  num_inserted: 5
  homology: 4
  random_break_features: true

  adjacent_length: 1000
  breakpoints_seed: 100
  dwgsim_seed: 100
  num_breakpoints: 10000
  num_concordant: 100000
