package:
  name: destruct
  version: '0.4.9'

source:
  git_url: https://dranew@bitbucket.org/dranew/destruct.git
  git_rev: v0.4.9

requirements:
  build:
    - python
    - scons
    - boost_lib ==1.60.0
    - tclap ==1.2.1
    - bzip2

  run:
    - python
    - boost_lib ==1.60.0
    - pandas >=0.17.1
    - pypeliner >=0.4.1
    - pygenes >=0.0.4
    - bowtie
    - pyyaml
    - matplotlib
    - seaborn
    - pysam

about:
  home: http://bitbucket.org/dranew/destruct
  license: MIT
  summary: 'Bioinformatics tool for joint prediction of rearrangement breakpoints from single or multiple tumour samples'

